[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[fuzz]
runs = 10000
dictionary_weight = 32

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
